### NumPy tutorial freecodecamp

In [1]:
import numpy as np

In [4]:
#The Basics

In [24]:
a = np.array([1, 2, 3], dtype='int32') #we can specify which dtype we want

In [6]:
a

array([1, 2, 3])

In [8]:
b = np.array([[4.0, 5.0, 6.0], [7.0, 8.0, 9.0]])

In [9]:
b

array([[4., 5., 6.],
       [7., 8., 9.]])

In [10]:
#Get Dimension

In [11]:
a.ndim

1

In [12]:
b.ndim

2

In [13]:
#Get Shape

In [14]:
a.shape

(3,)

In [15]:
b.shape

(2, 3)

In [16]:
#Get data type

In [20]:
a.dtype

dtype('int16')

In [18]:
b.dtype

dtype('float64')

In [21]:
# Get size

In [25]:
a.itemsize

4

In [23]:
b.itemsize

8

In [26]:
# Get size

In [27]:
a.size

3

In [28]:
b.size

6

In [29]:
# Get total size

In [31]:
a.size * a.itemsize

12

In [32]:
b.size * b.itemsize

48

In [33]:
a.nbytes

12

In [34]:
b.nbytes

48

### Accessing/Changing specific elements, rows, columns, etc

In [35]:
a = np.array([[1, 2, 3, 4, 5, 6, 7], [8, 9, 10, 11, 12, 13, 14]])

In [36]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [37]:
a.shape

(2, 7)

In [38]:
# Get a specific element [r, c]
a[0, 5]

6

In [39]:
# Get a specific row
a[0, :]

array([1, 2, 3, 4, 5, 6, 7])

In [40]:
# Get a specific column

In [41]:
a[ :, 1]

array([2, 9])

In [42]:
# Getting a little more fancy [startindex: endindex : stepsize]

In [43]:
a[0, 1:6:2]

array([2, 4, 6])

In [44]:
a[1, 5] = 20

In [45]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 20, 14]])

In [46]:
a[1, 5]

20

In [47]:
a[:,2] = [1, 2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


### 3D example

In [48]:
b = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [49]:
#Get specific element (work outside in)

In [50]:
b[0,1,1]

4

In [51]:
b[:,1,:]

array([[3, 4],
       [7, 8]])

In [52]:
# replace

In [53]:
b[:,1,:] = [[9,9], [8,8]]

In [54]:
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])

### Initializing different types of arrays

In [55]:
#all 0s matrix

In [59]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [61]:
# All 1s matrix
np.ones((4, 2, 2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [66]:
# Any other number
np.full((2, 2), 99)

array([[99, 99],
       [99, 99]])

In [68]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [69]:
np.full(a.shape, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [70]:
# Random decimal numbers
np.random.rand(4, 2)

array([[0.37063495, 0.98511681],
       [0.04376011, 0.71713505],
       [0.81197419, 0.5457993 ],
       [0.04032265, 0.3527451 ]])

In [71]:
np.random.random_sample(a.shape)

array([[0.49315951, 0.4018805 , 0.1359481 , 0.40182515, 0.98440234,
        0.14251325, 0.43983579],
       [0.72162215, 0.14569436, 0.45769026, 0.85388836, 0.59794269,
        0.84771504, 0.75987887]])

In [77]:
# Random Integer values
np.random.randint(4, 9, size=(3, 3))

array([[8, 5, 5],
       [6, 6, 8],
       [4, 5, 4]])

In [79]:
# The identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [88]:
# Repeat an array
arr = np.array([[1, 2, 3]])
r1 = np.repeat(arr, 3, axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [93]:
output = np.ones([5, 5])
print(output)

z = np.zeros([3,3])
z[1, 1] = 9
print(z)

output[1:4, 1:4] = z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


##### Be careful when copying arrays!!!

In [100]:
a = np.array([1, 2, 3])
b = a.copy()
b[0] = 100
b
a
print(a)
print(b)

[1 2 3]
[100   2   3]


### Mathematics

In [101]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [102]:
a + 2

array([3, 4, 5, 6])

In [103]:
a - 2

array([-1,  0,  1,  2])

In [104]:
a * 2

array([2, 4, 6, 8])

In [105]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [107]:
a += 2
a

array([5, 6, 7, 8])

In [108]:
b = np.array([1, 0, 1, 0])
a + b

array([6, 6, 8, 8])

In [109]:
a ** 2

array([25, 36, 49, 64])

In [111]:
# Take the sin of all values
np.cos(a)

array([ 0.28366219,  0.96017029,  0.75390225, -0.14550003])

##### Linear algebra

In [113]:
a = np.ones((2, 3))
print(a)
b = np.full((3, 2), 2)
print(b)

np.matmul(a, b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [114]:
# Find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

##### Statistics

In [116]:
stats = np.array([[1, 2, 3], [4, 5, 6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [117]:
np.min(stats)

1

In [120]:
np.max(stats, axis=1)

array([3, 6])

In [122]:
np.sum(stats, axis=0)

array([5, 7, 9])

### Reorganizing Arrays

In [135]:
before = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(before)

after = before.reshape((4, 2))
print(after)

[[1 2 3 4]
 [5 6 7 8]]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [140]:
# Vertically stacking vectors
# Vertical stack is denoted by "vstack"
v1 = np.array([1, 2, 3, 4])
v2 = np.array([5, 6, 7, 8])

np.vstack([v1, v2, v1, v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [143]:
# Horizontally stacking vectors
# Horizontal stack is denoted by "hstack"
h1 = np.ones((2, 4))
h2 = np.zeros((2, 2))

np.hstack([h1, h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

### Miscellaneous

##### Load data from file

In [157]:
filedata = np.genfromtxt('data.txt', delimiter=',')
filedata=filedata.astype('int32')
filedata

array([[     1,     13,    200,     11,    198,     76,     54,      3,
             2,     52,    765,     14,     74,     23,     96,     69,
           420,     21],
       [     2,     26,    400,     22,    396,    152,    108,      6,
             4,    104,   1530,     28,    148,     46,    192,    138,
           840,     42],
       [     1,    169,  40000,    121,  39204,   5776,   2916,      9,
             4,   2704, 585225,    196,   5476,    529,   9216,   4761,
        176400,    441]], dtype=int32)

##### Advanced Indexing

In [162]:
filedata[filedata > 900]

array([  1530,  40000,  39204,   5776,   2916,   2704, 585225,   5476,
         9216,   4761, 176400], dtype=int32)

In [168]:
# #  You can index with a list in NumPy
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
a[[1,2,8]]

array([2, 3, 9])

In [173]:
np.all(filedata > 500, axis=0)

array([False, False, False, False, False, False, False, False, False,
       False,  True, False, False, False, False, False, False, False])

In [176]:
(~((filedata > 50 ) & (filedata < 100)))
# ~ is not

array([[ True,  True,  True,  True,  True, False, False,  True,  True,
        False,  True,  True, False,  True, False, False,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True,  True,  True,  True,  True,  True,  True,  True,  True]])

In [181]:
array = np.array([[1, 2, 3], [4, 5, 6]])
array

array([[1, 2, 3],
       [4, 5, 6]])

In [184]:
print(array.sum(axis=1))      # Sum along rows


[ 6 15]


In [188]:
array = np.array([[1, 2, 3], [4, 5, 6]])


vector = np.array([1, 0, 1])
print(array + vector)

[[2 2 4]
 [5 5 7]]


In [189]:
from numpy.linalg import inv, det

matrix = np.array([[1, 2], [3, 4]])
   # Inverse
print(det(matrix)) 

-2.0000000000000004


In [190]:
rand_array = np.random.rand(2, 3)  # Uniformly distributed random numbers
print(rand_array)

[[0.39700424 0.51386726 0.05583505]
 [0.8470738  0.25536565 0.10715332]]


In [191]:
randn_array = np.random.randn(2, 3)  # Normally distributed random numbers
print(randn_array)

[[ 0.46854838 -0.34021998  0.71346749]
 [-0.5306051  -1.86723821 -1.29167648]]


In [194]:
array = np.array([1, 2, 3, 4, 5])
bool_index = array > 3
print(array[bool_index])  # Elements greater than 3


[4 5]


In [195]:
array = np.array([10, 20, 30, 40, 50])
indices = [1, 3, 4]
print(array[indices])  # Elements at positions 1, 3, and 4

[20 40 50]


In [197]:
data = np.array([(1, 'Alice', 25.0), (2, 'Bob', 45.5)], dtype=[('id', 'i4'), ('name', 'U10'), ('age', 'f4')])
print(data)
print(data['name'])  # Access by field name

[(1, 'Alice', 25. ) (2, 'Bob', 45.5)]
['Alice' 'Bob']


In [198]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([1, 0, 1])
print(array1 + array2)  # Broadcasting addition

[[2 2 4]
 [5 5 7]]


In [199]:
array = np.array([[1, 2, 3], [4, 5, 6]])

for row in array:
    print(row)

for element in array.flat:
    print(element)

[1 2 3]
[4 5 6]
1
2
3
4
5
6


In [200]:
array = np.array([1, 2, 3, 4])
print(np.sin(array))  # Apply sine function element-wise

[ 0.84147098  0.90929743  0.14112001 -0.7568025 ]


In [201]:
import time

# Using Python list
python_list = list(range(1000000))
start_time = time.time()
python_list = [x * 2 for x in python_list]
print("Python list time:", time.time() - start_time)

Python list time: 0.2669990062713623


In [203]:
# Using NumPy array
numpy_array = np.arange(1000000)
start_time = time.time()
numpy_array = numpy_array * 2
print("NumPy array time:", time.time() - start_time)

NumPy array time: 0.010727882385253906


In [204]:
array_c = np.array([[1, 2, 3], [4, 5, 6]], order='C')
array_f = np.array([[1, 2, 3], [4, 5, 6]], order='F')
print(array_c.flags)
print(array_f.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False

  C_CONTIGUOUS : False
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False



In [206]:
array = np.array([1, 2, np.nan, 4, 5])
print(np.isnan(array))  # Check for NaNs
print(np.nanmean(array))  # Compute mean ignoring NaNs

[False False  True False False]
3.0
